### ISSUE TITLE
Dependencies issue

### ISSUE THREAD

**Issue by ziggurat** [nkvoronov/skin.estuary-extended#4]
Hey, thank for doing this. Have one question: what are the dependencies for this to work?

I have jarvis 16.1 but when trying to install last master branch version it complaints about pvr.favourites dependency no met.

Any suggestions?

**Comment by nkvoronov** [comment]
https://github.com/nkvoronov/repository.yellowdragon/blob/jarvis/repo/repository.yellowdragon/repository.yellowdragon-16.1.110.zip
install repository for jarvis
OR
https://github.com/nkvoronov/script.pvr.favourites/tree/jarvis

**Comment by nkvoronov** [comment]
https://github.com/nkvoronov/repository.yellowdragon/tree/jarvis/repo

branch jarvis !!!!
not master

**Comment by nkvoronov** [comment]
http://xbmc.ru/forum/showpost.php?p=108296&postcount=1
